refugio/apps/adopcion/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path

# Aqui deben ir todas las urls de la aplicación
from refugio.apps.adopcion import views

app_name = 'adopcion'
urlpatterns = [
    path('', views.index_adopcion, name='home'),
    path('solicitud/listar/',  login_required(views.SolicitudList.as_view()), name='solicitud_listar'),
    path('solicitud/nuevo/',  login_required(views.SolicitudCreate.as_view()), name='solicitud_crear'),
    path('solicitud/editar/<int:pk>/',  login_required(views.SolicitudUpdate.as_view()), name='solicitud_editar'),
    path('solicitud/eliminar/<int:pk>/',  login_required(views.SolicitudDelete.as_view()), name='solicitud_eliminar'),
]

refugio/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView, PasswordResetView, LogoutView
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('refugio.apps.adopcion.urls'), name='home'),
    path('mascota/', include('refugio.apps.mascota.urls')),
    path('usuario/', include('refugio.apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
            name='password_reset_confirm'),
    path('reset/password_reset_complete',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

refugio/apps/adopcion/models.py
from django.db import models

# Create your models here.
# Informacion de persona que va a solicitar la adopcion de la mascota
# Field types: https://docs.djangoproject.com/en/3.1/ref/models/fields/#field-types

class Persona(models.Model):
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=75)
    telefono = models.CharField(max_length=12)
    edad = models.IntegerField()
    correo = models.EmailField()
    direccion = models.TextField(max_length=75)

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"


class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()

refugio/apps/adopcion/forms.py
from django import forms

from refugio.apps.adopcion.models import Persona, Solicitud


class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ['nombres', 'apellidos', 'telefono',
                  'edad', 'correo', 'direccion']
        labels = {'nombres': 'Nombres',
                  'apellidos': 'Apellidos',
                  'telefono': 'Telefono',
                  'edad': 'Edad',
                  'correo': 'Correo',
                  'direccion': 'Dirección'}
        widgets = {'nombres': forms.TextInput(attrs={'class': 'form-control'}),
                   'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
                   'telefono': forms.TextInput(attrs={'class': 'form-control'}),
                   'edad': forms.NumberInput(attrs={'class': 'form-control'}),
                   'correo': forms.EmailInput(attrs={'class': 'form-control'}),
                   'direccion': forms.TextInput(attrs={'class': 'form-control'}),
                   }


class SolicitudForm(forms.ModelForm):
    class Meta:
        model = Solicitud
        fields = ['numero_mascotas', 'razones']
        labels = {'numero_mascotas': 'Número de Mascotas',
                  'razones': 'Razones para adoptar'}
        widgets = {'numero_mascotas': forms.TextInput(attrs={'class': 'form-control'}),
                   'razones': forms.Textarea(attrs={'class': 'form-control'})
                   }

refugio/apps/adopcion/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from refugio.apps.adopcion.forms import SolicitudForm, PersonaForm
from refugio.apps.adopcion.models import Solicitud, Persona


def index_adopcion(request):
    return render(request, 'base/home.html')


class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'


class SolicitudCreate(CreateView):
    model = Solicitud
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit=False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))


# Construido en el video https://youtu.be/sJtTeZvLEy8?list=PLsRdPvQ2xMkH8c2BOnQ_O1KZ9lyyL_eGB&t=87
class SolicitudUpdate(UpdateView):
    model = Solicitud
    second_model = Persona
    form_class = SolicitudForm
    template_name = 'adopcion/solicitud_form.html'
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        solicitud = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_solicitud = kwargs['pk']
        solicitud = self.model.objects.get(id=id_solicitud)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        form = self.form_class(request.POST, instance=solicitud)
        form2 = self.second_form_class(request.POST, instance=persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())


class SolicitudDelete(DeleteView):
    model = Solicitud
    template_name = 'adopcion/solicitud_delete.html'
    success_url = reverse_lazy('adopcion:solicitud_listar')

templates/adopcion/solicitud_delete.html
{% extends 'base/home.html' %}
{% block bienvenido %}{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form role="form" method="post">
                {% csrf_token %}
                <h3>Desea eliminar el registro # {{ object.id }} de {{ object.persona.nombres }} {{ object.persona.apellidos }} ?</h3>
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Si, Eliminar</button>
                <a class="btn btn-default" href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

{% endblock %}

templates/adopcion/solicitud_form.html
{% extends 'base/home.html' %}
{% block bienvenido %}{% endblock %}
{% block title%} Solicitud Nueva {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form role="form" method="post">
                {% csrf_token %}
                {{ form2.as_p }}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/home.html' %}
{% block bienvenido %}{% endblock %}
{% block title%} Solicitudes de Adopción {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <table class="table table-sm table-hover">
                <thread>
                    <tr>
                        <td>N° de Solicitud</td>
                        <td>Adoptante</td>
                        <td>N° de Mascotas</td>
                        {% comment %}<td>Razones</td>{% endcomment %}
                        <td colspan="2">Acciones</td>
                    </tr>
                </thread>
                <tbody>
                {% if object_list %}
                {% for solicitud in object_list %}
                <tr>
                    <td>{{ solicitud.id }}</td>
                    <td>{{ solicitud.persona.nombres }} {{ solicitud.persona.apellidos }}</td>
                    <td>{{ solicitud.numero_mascotas }}</td>
                    {% comment "No es necesario actualmente" %}<td>{{ solicitud.razones }}</td>{% endcomment %}
                    <td>
                        <a class="btn btn-primary btn-sm" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
                    </td>
                    <td>
                       <a class="btn btn-danger btn-sm"
                           href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
                    </td>{% comment "Optional note" %}{% endcomment %}
                </tr>
                {% endfor %}
                {% else %}
                <h4 class="alert alert-warning" role="alert">No hay adopciones registradas.</h4>
                {% endif %}
                </tbody>
            </table>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}