refugio/apps/adopcion/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path

# Aqui deben ir todas las urls de la aplicación
from refugio.apps.adopcion import views

app_name = 'adopcion'
urlpatterns = [
    path('', views.index_adopcion, name='home'),
    path('solicitud/listar/',  login_required(views.SolicitudList.as_view()), name='solicitud_listar'),
    path('solicitud/nuevo/',  login_required(views.SolicitudCreate.as_view()), name='solicitud_crear'),
    path('solicitud/editar/<int:pk>/',  login_required(views.SolicitudUpdate.as_view()), name='solicitud_editar'),
    path('solicitud/eliminar/<int:pk>/',  login_required(views.SolicitudDelete.as_view()), name='solicitud_eliminar'),
]

refugio/apps/mascota/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path

# Aqui deben ir todas las urls de la aplicación
from refugio.apps.mascota import views

app_name = 'mascota'
urlpatterns = [
    path('', views.index_mascota, name='index'),
    path('nuevo/', login_required(views.MascotaCreate.as_view()), name='mascota_crear'),
    path('listar/', login_required(views.MascotaList.as_view()), name='mascota_listar'),
    path('editar/<int:pk>/', login_required(views.MascotaUpdate.as_view()), name='mascota_editar'),
    path('eliminar/<int:pk>/', login_required(views.MascotaDelete.as_view()), name='mascota_eliminar'),
    path('listado/', views.listadodemascotas, name='listado')
]

refugio/apps/usuario/urls.py
from django.contrib import admin
from django.urls import path

# Aqui deben ir todas las urls de la aplicación
from refugio.apps.usuario import views

app_name = 'usuario'
urlpatterns = [
    # path('', views.index_adopcion, name='index'),
    path('registrar/', views.RegistroUsuario.as_view(), name='registrar'),
]

refugio/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView, PasswordResetView, LogoutView
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('refugio.apps.adopcion.urls'), name='home'),
    path('mascota/', include('refugio.apps.mascota.urls')),
    path('usuario/', include('refugio.apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
            name='password_reset_confirm'),
    path('reset/password_reset_complete',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3>Entra en Contacto</h3>
                <address>
                    +57 311 994 11855
                    <br/>
                    <a href="mailto:{{ contato_email }}" class="text-light">{{ contato_email }}</a>
                </address>
            </div>
        </div>
    </div>
    <div class="rights pb-4">
        <div class="container-fluid">
            <div class="row">
                <div class="col">{% now 'Y' %} Adopcion de Animales. Todos los derechos reservados.</div>
            </div>
        </div>
    </div>
</footer>

templates/base/header-before-login.html
{% block header-before-login %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'adopcion:home' %}">Home</a>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                    <!-- Parte derecha del Header -->
                    <ul class="navbar-nav ml-md-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                               data-toggle="dropdown">Menú</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider">
                                </div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>
{% endblock%}

templates/base/header.html
{% block header %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="navbar-toggler-icon"></span>
				</button> <a class="navbar-brand" href="{% url 'adopcion:home' %}">Home</a>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="navbar-nav">
                        <!-- Comentando Links al lado del Home
						<li class="nav-item active">
							 <a class="nav-link" href="#">Link PP<span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							 <a class="nav-link" href="#">Link KK</a>
						</li>
						-->
						<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Mascotas</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								<a class="dropdown-item" href="{% url 'mascota:mascota_crear' %}">Registrar</a>
                                <a class="dropdown-item" href="{% url 'mascota:mascota_listar' %}">Listar</a>
                                <!-- Comentando código innecesário
                                <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                                -->
							</div>
						</li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Adopciones</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								<a class="dropdown-item" href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a>
                                <a class="dropdown-item" href="{% url 'adopcion:solicitud_listar' %}">Ver Solicitudes</a>
                                <!-- Comentando código innecesário
                                <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                                -->
							</div>
						</li>
					</ul>
					<!-- Comentando el Campo de Búsqueda
                    <form class="form-inline">
						<input class="form-control mr-sm-2" type="text" />
						<button class="btn btn-primary my-2 my-sm-0" type="submit">
							Search
						</button>
					</form>-->
                    <!-- Parte derecha del Header -->
                    <ul class="navbar-nav ml-md-auto">
				<!--	<li class="nav-item active">
							 <a class="nav-link" href="{% url 'adopcion:home' %}">Refugio<span class="sr-only">(current)</span></a>
						</li>-->
						<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Opciones</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
								<a class="dropdown-item" href="{% url 'usuario:registrar' %}"><i class="fas fa-user-plus"></i> Agregar Usuario</a>
								<div class="dropdown-divider">
								</div> <a class="dropdown-item" href="{% url 'logout' %}">Salir</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
</div>
{% endblock %}

templates/base/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Documentación de Templates Tags https://docs.djangoproject.com/en/3.2/ref/templates/builtins/ -->
    {% block extrastatic %}
    {% endblock %}
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}" crossorigin="anonymous">
    <!-- Font Boostrap CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" crossorigin="anonymous">
    <!-- Font Personal CSS -->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Generado en https://gauger.io/fonticon/-->
    <link rel="shortcut icon" type="image/jpg" href="{% static 'img/favicon.ico' %}"/>

    <title>{% block title%} Adopcion de Animales {% endblock %}</title>
</head>
<body class="footer-fijo">
{% block header %}
{% include 'base/header.html' %}
{% endblock %}
<div class="contenido-body">
    {% block bienvenido %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h2>Bienvenido, quieres adoptar un hermoso animal ?</h2>
                    <p>
                        Este refugio es considerado el más cuidadoso y considerado punto de adopción de la ciudad.
                        Esperemos te sientas cómodo en nuestra página web.
                    </p>
                    <p>
                        <a class="btn btn-primary btn-large" href="#">Más Información</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form role="form">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" id="exampleInputEmail1">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">File input</label>
                        <input type="file" class="form-control-file" id="exampleInputFile">
                        <p class="help-block">Example block-level help text here.</p>
                    </div>
                    <div class="checkbox">

                        <label>
                            <input type="checkbox"> Check me out
                        </label>
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
    {% endblock %}
</div>
{% block footer %}
{% include 'base/footer.html' %}
{% endblock %}

{% block extrajs %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/javascript.js' %}" crossorigin="anonymous"></script>
</body>
</html>