refugio/apps/mascota/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path

# Aqui deben ir todas las urls de la aplicación
from refugio.apps.mascota import views

app_name = 'mascota'
urlpatterns = [
    path('', views.index_mascota, name='index'),
    path('nuevo/', login_required(views.MascotaCreate.as_view()), name='mascota_crear'),
    path('listar/', login_required(views.MascotaList.as_view()), name='mascota_listar'),
    path('editar/<int:pk>/', login_required(views.MascotaUpdate.as_view()), name='mascota_editar'),
    path('eliminar/<int:pk>/', login_required(views.MascotaDelete.as_view()), name='mascota_eliminar'),
    path('listado/', views.listadodemascotas, name='listado')
]

refugio/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView, PasswordResetView, LogoutView
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('refugio.apps.adopcion.urls'), name='home'),
    path('mascota/', include('refugio.apps.mascota.urls')),
    path('usuario/', include('refugio.apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
            name='password_reset_confirm'),
    path('reset/password_reset_complete',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

refugio/apps/mascota/models.py
from django.db import models

# Create your models here.
from refugio.apps.adopcion.models import Persona


class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.nombre}"


class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_de_rescate = models.DateField()
    raza = models.CharField(max_length=10)
    comentarios = models.CharField(max_length=100)
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

    def __str__(self):
        return f"{self.nombre}"

refugio/apps/mascota/forms.py
from django import forms

from refugio.apps.mascota.models import Mascota


class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        fields = ['nombre', 'sexo', 'edad_aproximada',
                  'fecha_de_rescate', 'raza', 'comentarios', 'persona',
                  'vacuna']
        labels = {'nombre': 'Nombre',
                  'sexo': 'Sexo',
                  'edad_aproximada': 'Edad Aproximada',
                  'fecha_de_rescate': 'Fecha de Rescate',
                  'raza': 'Raza',
                  'comentarios': 'Comentarios',
                  'persona': 'Adoptante',
                  'vacuna': 'Vacuna'
                  }
        widgets = {'nombre': forms.TextInput(attrs={'class': 'form-control'}),
                   'sexo': forms.TextInput(attrs={'class': 'form-control'}),
                   'edad_aproximada': forms.TextInput(attrs={'class': 'form-control'}),
                   'fecha_de_rescate': forms.TextInput(attrs={'class': 'form-control'}),
                   'raza': forms.TextInput(attrs={'class': 'form-control'}),
                   'comentarios': forms.TextInput(attrs={'class': 'form-control'}),
                   'persona': forms.Select(attrs={'class': 'custom-select'}),
                   'vacuna': forms.CheckboxSelectMultiple(),
                   }

refugio/apps/mascota/views.py
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from refugio.apps.mascota.forms import MascotaForm
from refugio.apps.mascota.models import Mascota


def index_mascota(request):
    return render(request, 'mascota/mascota.html')


def mascota_create(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mascota:mascota_listar'))
        else:
            return render(request, 'mascota/mascota_form.html', {'form': form}, status=400)

    form = MascotaForm()
    return render(request, 'mascota/mascota_form.html', context={'form': form})


def mascota_list(request):
    mascota = Mascota.objects.all().order_by('id')
    return render(request, 'mascota/mascota_list.html', context={'mascotas': mascota})


def mascota_edit(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('mascota:mascota_listar'))
    return render(request, 'mascota/mascota_form.html', context={'form': form})


def mascota_delete(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return HttpResponseRedirect(reverse('mascota:mascota_listar'))
    return render(request, 'mascota/mascota_delete.html', context={'mascota': mascota})


# Intro https://docs.djangoproject.com/en/3.2/topics/class-based-views/
# Detailed https://docs.djangoproject.com/en/3.2/ref/class-based-views/

# Cuando la vista es llamada, se va hacia template_name.
class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'


class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')


class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')


class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')


def listadodemascotas(request):
    lista = serializers.serialize('json', Mascota.objects.all())
    return HttpResponse(lista, content_type='application/json')

templates/mascota/mascota.html
{% extends 'base/home.html' %}

{% block title %} App Mascota {% endblock %}
{% block bienvenido %}{% endblock %}
{% block content %}
<div class="row">
            <div class="col-md-4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <div class="col-md-4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <div class="col-md-4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
        </div>
{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/home.html' %}
{% block bienvenido %}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
            <form role="form" method="post">
                {% csrf_token %}
                <h3>Desea eliminar el registro de {{ object.nombre }} ?</h3>
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Si, Eliminar</button>
                <a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
            </form>
        </div>
    <div class="col-md-3"></div>
</div>

{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/home.html' %}
{% block bienvenido %}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
            <form role="form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <!--<div class="form-group">
                    <label for="exampleInputEmail1">Dirección de Email</label>
                    <input type="email" class="form-control" id="exampleInputEmail1">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Contraseña</label>
                    <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">Seleccione Archivo...</label>
                    <input type="file" class="form-control-file" id="exampleInputFile">
                    <p class="help-block">Example block-level help text here.</p>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Check me out
                    </label>
                </div>-->
                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    <div class="col-md-3"></div>
</div>

{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/home.html' %}
{% block bienvenido %}{% endblock %}
{% block title%} Mascotas Adoptadas {% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <table class="table table-sm table-hover">
            <thread>
                <tr>
                    <td>#</td>
                    <td>Nombre</td>
                    <td>Sexo</td>
                    <td>Edad</td>
                    <td>Raza</td>
                    <td>Fecha de Rescate</td>
                    <td>Adoptante</td>
                    <td colspan="2">    Acciones   </td>
                </tr>
            </thread>
            <tbody>
            {% if object_list %}
            {% for mascota in object_list %}
            <tr>
                <td>{{ mascota.id }}</td>
                <td>{{ mascota.nombre }}</td>
                <td>{{ mascota.sexo }}</td>
                <td>{{ mascota.edad_aproximada }}</td>
                <td>{{ mascota.raza }}</td>
                <td>{{ mascota.fecha_de_rescate }}</td>
                <td>{{ mascota.persona.nombres }} {{mascota.persona.apellidos }}</td>
                <td>
                    <a class="btn btn-primary btn-sm" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                </td>
                <td>
                    <a class="btn btn-danger btn-sm" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <h1 class="alert alert-warning" role="alert">No hay registro de mascotas</h1>
            {% endif%}
            </tbody>
        </table>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}